# Generated by Django 3.1.5 on 2021-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
